on: push
name: Build Angular
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and npm run build
        run: |
          npm i
          npm run build --prod

      - name: List output files
        run: ls

#      - name: Push Build to Releases
#        uses: ncipollo/release-action@v1
#        with:
#          artifacts: "dist/angular-githubaction/*"
#          token: ${{ secrets.TOKEN }}

#      - name: FTP-Deploy-Action
#          uses: SamKirkland/FTP-Deploy-Action@2.0.0
#          env:
#            FTP_SERVER: ${{ secrets.FTP_SERVER }}
#            FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
#            FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
#            LOCAL_DIR: "dist/angular-githubaction/*"
#            METHOD: ftp
#            PORT: 21
#            ARGS: --delete
